### ISSUE TITLE
  COPYING file includes GPL

### ISSUE THREAD

**Issue by campd** [libimobiledevice/libplist#48]
There's a GPL COPYING file in addition to the LGPL COPYING.LESSER file in the root directory.
It looks like all the source files are LGPLed.  Is the GPL inclusion a mistake, or are there pieces of code I missed that are GPLed here?

**Comment by saurik** [comment]
"If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights."

**Comment by Alex-Vaduva** [comment]
> "If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights."

As an FYI:
This is only available for LGPL version 3 (which is specified at the beginning of the license). For LGPL version 2.1 (and 2.0), it is not needed to include the full text of GPL-2.0
