### ISSUE TITLE
Parsing dates depends on timezone and, specifically, on Daylight Saving Time

### ISSUE THREAD

**Issue by kosmakoff** [libimobiledevice/libplist#75]
I see issues when parsing XML to plist_node. The issue is that when it comes to parsing date value, it adds unnecessary 1 hour shift for my current timezone.

I use this XML to import:

```
<?xml version=""1.0"" encoding=""UTF-8""?>
<!DOCTYPE plist PUBLIC ""-//Apple//DTD PLIST 1.0//EN"" ""http://www.apple.com/DTDs/PropertyList-1.0.dtd"">
<plist version=""1.0"">
<dict>
    <key>Last Backup Date</key>
    <date>2016-04-06T10:16:17Z</date>
</dict>
</plist>
```

After loading it via `plist_from_xml`, after getting the key `Last Backup Date` and converting it to string value, I see the value of `2016-04-06 11:16:17`, which is 1 hour more than I expect to see.

I think the issue is in this [line](https://github.com/libimobiledevice/libplist/blob/master/src/xplist.c#L461).  GMT is not UTC, and it can have daylight saving time, hence the error.

**Comment by nikias** [comment]
@kosmakoff I don't think this is a bug. You say "converting it to string value", how exactly do you do that? If the XML file says 10:16 the output 10:16 would be correct since the date does not contain any timezone information. If you get a different output for the date value before and after the DST change then this would be a bug.

**Comment by kosmakoff** [comment]
Silly me, I wrote 2 identical timestamps back then. Let me just fix that.

**Comment by nikias** [comment]
If you really think this is a bug, please give a code example in C. Please tell me how you traverse the resulting plist structure and how you get the value of the datetime node.

From the manpage (man gmtime):

> The functions ctime(), gmtime(), and localtime() all take as an argument a time value representing the time in seconds since the Epoch (00:00:00 UTC, January 1, 1970; see time(3)).

You say "parse that XML as a string", does it basically mean using plist_from_xml() ?

If I do that, and then get the value of the date node, I get the numerical value 481630577 which is the number of seconds since Jan 1, 1970 UTC. Now I can output that timestamp but functions like ```ctime()``` are respecting the current user's timezone setting. Using the command ```date -r 481630577``` I am getting this output (I'm on CEST right now):
```
$ date -r 481630577
Sa  6 Apr 1985 12:16:17 CEST
```
while when setting the UTC timezone I will get:
```
$ TZ=UTC date -r 481630577
Sa  6 Apr 1985 10:16:17 UTC
```
or even GMT:
```
$ TZ=GMT date -r 481630577
Sa  6 Apr 1985 10:16:17 GMT
```
The thing is, it depends on how you convert/parse the time information. If I use ```gmtime()``` in my code and use ```strftime()``` to convert the datetime to a string, I get 10:16:17, while when using ```localtime()``` I get 12:16:17.

**Comment by nikias** [comment]
@kosmakoff can you tell me how you convert the date to a string? I can't fix  problem that can't be confirmed.

**Comment by kosmakoff** [comment]
Hi. Sorry for slow response times, I just can't allocate enough time to finish this issue once and forever.

Right now here are 2 source codes which I tried to test.
First is the C# code with DLL wrapper. [Here it is](https://gist.github.com/kosmakoff/1da2424447566c8c64de9d8fa1c6d32a). The output of the program is in the comments section.

I could not reproduce the issue on Ubuntu Linux on natively built libs, so I suspect the issue is in the Windows build which I get from [Quamotion](http://quamotion.mobi/iMobileDevice/Download). I don't know how they build it, but I'm going to figure it out, and find where the problem is.

**Comment by kosmakoff** [comment]
Seems like #56 is related to this issue. I just tried to create the plist with pre-1970 date and when converted to XML it generated null in place of date value. Interestingly though, the conversion from/to binary format does not contain any issues.

To sum up:
plist from xml - has issue
plist to xml - correct
plist from binary - correct
plist to binary - correct

**Comment by nikias** [comment]
@kosmakoff can you check this with the latest code? I made a bunch of changes regarding the date format etc.

**Comment by kosmakoff** [comment]
@nikias Could you point to exact lines of code that were changed? I'd like to compare the source code with quamotion's.

**Comment by kosmakoff** [comment]
Verified with the latest version based on Quamotion's fork. The issue's gone.

**Comment by nikias** [comment]
AWESOME!
